# Generated by Django 6.1.1 on 2026-09-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bidding', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(db_column='listingId', on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='catalog.listing'),
        ),
        migrations.AddConstraint(
            model_name='bid',
            constraint=models.UniqueConstraint(fields=('listing', 'bidder'), name='unique_bid_per_listing_per_bidder'),
        ),
    ]
