# Generated by Django 6.1.1 on 2026-09-27 19:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerVerificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verification_status', models.CharField(choices=[('unverified', 'Unverified'), ('pending', 'Pending'), ('verified', 'Verified'), ('rejected', 'Rejected')], db_column='verificationStatus', max_length=12)),
                ('verification_note', models.TextField(blank=True, db_column='verificationNote', null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('seller', models.ForeignKey(db_column='sellerId', on_delete=django.db.models.deletion.CASCADE, related_name='verification_logs', to='accounts.seller')),
            ],
            options={
                'db_table': 'sellerVerificationLogs',
                'ordering': ['-created_at'],
            },
        ),
    ]
