# Generated by Django 6.1.1 on 2026-10-07 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_sellerverificationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='type',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('admin', 'Admin')], max_length=20),
        ),
    ]
