# Generated by Django 6.1.1 on 2026-09-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('buyer', models.ForeignKey(db_column='buyerId', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.user')),
                ('listing', models.ForeignKey(blank=True, db_column='listingId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversations', to='catalog.listing')),
                ('seller', models.ForeignKey(db_column='sellerId', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='accounts.seller')),
            ],
            options={
                'db_table': 'conversations',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('sender_id', models.BigIntegerField(db_column='senderId')),
                ('sender_type', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller')], db_column='senderType', max_length=10)),
                ('body', models.TextField(blank=True, null=True)),
                ('attachment_path', models.CharField(blank=True, db_column='attachmentPath', max_length=255, null=True)),
                ('attachment_url', models.URLField(blank=True, db_column='attachmentUrl', max_length=500, null=True)),
                ('seen_at', models.DateTimeField(blank=True, db_column='seenAt', null=True)),
                ('conversation', models.ForeignKey(db_column='conversationId', on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='messaging.conversation')),
            ],
            options={
                'db_table': 'messages',
                'ordering': ['created_at'],
            },
        ),
    ]
