# Generated by Django 6.1.1 on 2026-09-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuoteRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('qty', models.BigIntegerField()),
                ('message', models.TextField()),
                ('contact_name', models.CharField(blank=True, db_column='contactName', max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, db_column='contactEmail', max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, db_column='contactPhone', max_length=32, null=True)),
                ('contact_company', models.CharField(blank=True, db_column='contactCompany', max_length=255, null=True)),
                ('contact_city', models.CharField(blank=True, db_column='contactCity', max_length=255, null=True)),
                ('contact_road', models.CharField(blank=True, db_column='contactRoad', max_length=255, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('responded', 'Responded'), ('closed', 'Closed')], default='new', max_length=10)),
                ('buyer', models.ForeignKey(blank=True, db_column='buyerId', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quote_requests', to='accounts.user')),
                ('listing', models.ForeignKey(db_column='listingId', on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='catalog.listing')),
                ('seller', models.ForeignKey(db_column='sellerId', on_delete=django.db.models.deletion.CASCADE, related_name='quote_requests', to='accounts.seller')),
            ],
            options={
                'db_table': 'quoteRequests',
                'ordering': ['-created_at'],
            },
        ),
    ]
