# Generated by Django 6.1.1 on 2026-09-25 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Favourite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('listing', models.ForeignKey(db_column='listingId', on_delete=django.db.models.deletion.CASCADE, related_name='favourited_by', to='catalog.listing')),
                ('user', models.ForeignKey(db_column='userId', on_delete=django.db.models.deletion.CASCADE, related_name='favourites', to='accounts.user')),
            ],
            options={
                'db_table': 'favourites',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('rating', models.PositiveSmallIntegerField()),
                ('content', models.TextField(blank=True, null=True)),
                ('seller_reply', models.TextField(blank=True, db_column='sellerReply', null=True)),
                ('listing', models.ForeignKey(db_column='listingId', on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='catalog.listing')),
            ],
            options={
                'db_table': 'reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
