# Generated by Django 6.1.1 on 2026-09-21 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('country_code', models.CharField(db_column='countryCode', max_length=10)),
                ('flag_path', models.CharField(blank=True, db_column='flagPath', max_length=255, null=True)),
                ('flag_url', models.URLField(blank=True, db_column='flagUrl', max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'db_table': 'countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('state_code', models.CharField(db_column='stateCode', max_length=20)),
                ('flag_path', models.CharField(blank=True, db_column='flagPath', max_length=255, null=True)),
                ('flag_url', models.URLField(blank=True, db_column='flagUrl', max_length=500, null=True)),
                ('country', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.CASCADE, related_name='states', to='geography.country')),
            ],
            options={
                'db_table': 'states',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('city_code', models.CharField(db_column='cityCode', max_length=20)),
                ('flag_path', models.CharField(blank=True, db_column='flagPath', max_length=255, null=True)),
                ('flag_url', models.URLField(blank=True, db_column='flagUrl', max_length=500, null=True)),
                ('country', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.country')),
                ('state', models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, related_name='cities', to='geography.state')),
            ],
            options={
                'verbose_name_plural': 'cities',
                'db_table': 'cities',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thana',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('updated_by', models.BigIntegerField(blank=True, db_column='updatedBy', null=True)),
                ('updater_type', models.CharField(blank=True, choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='updaterType', max_length=10, null=True)),
                ('updater_name', models.CharField(blank=True, db_column='updaterName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updatedAt')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('thana_code', models.CharField(db_column='thanaCode', max_length=20)),
                ('flag_path', models.CharField(blank=True, db_column='flagPath', max_length=255, null=True)),
                ('flag_url', models.URLField(blank=True, db_column='flagUrl', max_length=500, null=True)),
                ('city', models.ForeignKey(db_column='cityId', on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='geography.city')),
                ('country', models.ForeignKey(db_column='countryId', on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='geography.country')),
                ('state', models.ForeignKey(db_column='stateId', on_delete=django.db.models.deletion.CASCADE, related_name='thanas', to='geography.state')),
            ],
            options={
                'verbose_name_plural': 'thanas',
                'db_table': 'thanas',
                'ordering': ['name'],
            },
        ),
    ]
