# Generated by Django 6.1.1 on 2026-09-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geography', '0002_alter_state_slug_state_unique_state_slug_per_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AlterField(
            model_name='thana',
            name='slug',
            field=models.SlugField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='city',
            constraint=models.UniqueConstraint(fields=('state', 'slug'), name='unique_city_slug_per_state'),
        ),
        migrations.AddConstraint(
            model_name='thana',
            constraint=models.UniqueConstraint(fields=('city', 'slug'), name='unique_thana_slug_per_city'),
        ),
    ]
