# Generated by Django 6.1.1 on 2026-09-28 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_listing_deleted_at_listing_moderation_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='moderation_note',
        ),
        migrations.AddField(
            model_name='listing',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='ListingStatusChangeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested')], max_length=18)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_by', models.BigIntegerField(blank=True, db_column='createdBy', null=True)),
                ('creator_type', models.CharField(choices=[('admin', 'Admin'), ('seller', 'Seller'), ('user', 'User'), ('system', 'System')], db_column='creatorType', default='system', max_length=10)),
                ('creator_name', models.CharField(blank=True, db_column='creatorName', max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='createdAt')),
                ('listing', models.ForeignKey(db_column='listingId', on_delete=django.db.models.deletion.CASCADE, related_name='status_change_logs', to='catalog.listing')),
            ],
            options={
                'db_table': 'listingStatusChangeLogs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='ListingModerationLog',
        ),
    ]
