# Generated by Django 6.1.1 on 2026-09-25 04:37

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('notifiable_type', models.CharField(max_length=255)),
                ('notifiable_id', models.BigIntegerField()),
                ('type', models.CharField(max_length=255)),
                ('data', models.TextField()),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['notifiable_type', 'notifiable_id'], name='notif_notifiable_idx')],
            },
        ),
    ]
